name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci-pipeline:
    name: CI Pipeline
    runs-on: ubuntu-latest

    env:
      # Ustaw zmienne środowiskowe (secrets)
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}

    steps:
    # Checkout kodu
    - name: Checkout code
      uses: actions/checkout@v3

    # Setup Python
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    # Instalacja narzędzi formatowania i lintowania
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff black

    # Lintowanie kodu za pomocą Ruff
    - name: Run Ruff
      run: ruff . --fix

    # Formatowanie kodu za pomocą Black
    - name: Run Black
      run: black .

    # Setup Dockera
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    # Build i uruchomienie kontenerów Docker
    - name: Build and Start Docker Containers
      run: docker-compose up --build -d

    # Sprawdzenie statusu kontenerów
    - name: Verify Docker Containers
      run: docker ps

    # Wykonywanie testów wewnątrz Dockera
    - name: Run tests in Docker
      run: docker-compose exec app pytest

    # Wyłączenie Dockera po zakończeniu
    - name: Tear down Docker
      if: always()
      run: docker-compose down
